version: '3.4'

x-main: &main
  tty: true
  stdin_open: true
  build: .
  volumes:
    - '.:/app'
  environment:
    - DB_HOST=postgres
    - DB_USERNAME=postgres
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis'
    volumes:
      - 'redis:/data'

  sidekiq:
    <<: *main
    command: sidekiq

  website:
    <<: *main
    ports:
      - '3000:3000'

volumes:
  postgres:
  redis:

