version: "3.9"

networks:
  happy_software:
    name: happy_network

services:
  db:
    image: 'postgres:13.2-alpine'
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
    networks:
      - default
      - happy_software
    volumes:
      - '.:/myapp'
    depends_on:
      - db

volumes:
  postgres:
