version: "3.9"
services:
  db:
    image: 'postgres:13.2-alpine'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
