default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: happy_house_development

test:
  <<: *default
  database: happy_house_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_URL") { 'happy_house_production' } %>
