default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: postgres

development:
  <<: *default
  database: happy_house_development
  username: postgres
  password:

test:
  <<: *default
  host: 
  database: happy_house_test
  username: postgres
  password:

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_URL") { 'happy_house_production' } %>
