test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
 service: S3
 access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
 secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
 region: us-east-1
 bucket: myhappyhouse

#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
