name: Ruby

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run database setup
        run: |
          sudo apt-get install libpq-dev
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

      - name: Run rspec tests
        run: bundle exec rspec
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
